### PR TITLE
[major] added i18next support and ability to consume children from te…

### PR DESCRIPTION
**Pull request by daniloster**
…mplate string

## Description

Added support for i18next and releasing version `1.0.0`

## Changes

- Added support for `i18next`
- Added ability to consume `children` from the template string (see `docs/GETTING_STARTED.md`)

## Tests

- [x] Manually Tested
- [x] Unit Tested
- [ ] Visually Tested

### CODE REVIEW

**Comment by adrai** [comment]
How would an i18next example look like when loading translations asynchronously i.e. With i18next-http-backend ?
Is there something like hasNamespaceLoaded? https://github.com/i18next/react-i18next/blob/master/src/utils.js#L43
not to render (or render a fallback ui) until the namespace is loaded?

**Comment by adrai** [comment]
for example, when using an i18next config like this:
image

**Comment by adrai** [comment]
@daniloster do you know what I mean?

**Comment by adrai** [comment]
I think something like this should be done somewhere: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L32
but I have no idea how... 🤷‍♂️

**Comment by daniloster** [comment]
Hi @adrai , I am going to create an issue so we have better discussion there and it server as guide to whoever is trying to use as well.

https://github.com/daniloster/svelte-i18n/issues/10

**Pull request merged**
